export const accounts = [
  "Baker Hughes",
  "General Mills",
  "Wynn Resorts",
  "Hyatt Hotels",
  "Fossil Group",
  "Wyndham Worldwide",
  "Education Management",
  "Mondelez International",
  "Boyd Gaming",
  "PepsiCo",
  "JetBlue Airways",
  "AutoNation",
  "Marriott International",
  "Interpublic Group",
  "Under Armour",
  "Activision Blizzard",
  "Helmerich & Payne",
  "Rush Enterprises",
  "Oracle",
  "Ralph Lauren",
  "Hanesbrands",
  "Lithia Motors",
  "Guess",
  "Microsoft",
  "Las Vegas Sands",
  "Penske Automotive Group",
  "Synopsys",
  "Columbia Sportswear",
  "FedEx",
  "G-III Apparel Group",
  "Avis Budget Group",
  "Hormel Foods",
  "Group 1 Automotive",
  "Wolverine World Wide",
  "Take-Two Interactive Software",
  "Superior Energy Services",
  "Pinnacle Foods",
  "Big Heart Pet Brands",
  "VF",
  "Kraft Foods Group",
  "H.J. Heinz",
  "Delta Air Lines",
  "Cameron International",
  "Caesars Entertainment",
  "Alaska Air Group",
  "Regency Energy Partners",
  "ConAgra Foods",
  "J.M. Smucker",
  "Seventy Seven Energy",
  "salesforce.com",
  "TreeHouse Foods",
  "Penn National Gaming",
  "Flowers Foods",
  "Skechers U.S.A.",
  "Symantec",
  "Hilton Worldwide Holdings",
  "Graham Holdings",
  "National Oilwell Varco",
  "Patterson-UTI Energy",
  "Carters",
  "Campbell Soup",
  "SkyWest",
  "Oceaneering International",
  "Hain Celestial Group",
  "CarMax",
  "MGM Resorts International",
  "Hawaiian Holdings",
  "Levi Strauss",
  "Willbros Group",
  "Apollo Education Group",
  "Pinnacle Entertainment",
  "Starwood Hotels & Resorts",
  "Autodesk",
  "Electronic Arts",
  "RPC",
  "Asbury Automotive Group",
  "American Airlines Group",
  "Mead Johnson Nutrition",
  "Dean Foods",
  "Post Holdings",
  "Southwest Airlines",
  "Intuit",
  "Teradata",
  "United Continental Holdings",
  "CA",
  "Sonic Automotive",
  "UPS",
  "WhiteWave Foods",
  "FMC Technologies",
  "Nike",
  "Kellogg",
  "Oil States International",
  "Adobe Systems",
  "Exterran Holdings",
  "Hillshire Brands",
  "Land O-Lakes",
  "Halliburton",
  "McCormick",
  "PVH",
  "Hershey",
  "Coach",
  "MRC Global",
  "Omnicom Group",
];
